<?php

/**
 * @file
 * Hook implementations of the Scheduler API Test module.
 */

/**
 * Implements hook_scheduler_allow_publishing().
 */
function scheduler_api_test_scheduler_allow_publishing($node) {
  // If there is no 'approved' field do nothing to change the result.
  if (!isset($node->field_approved)) {
    $allowed = TRUE;
  }
  else {
    // Only publish nodes that have the 'Approved' checkbox ticked.
    $allowed = $node->field_approved->value;
    // If publication is denied then inform the user why.
    if (!$allowed) {
      drupal_set_message(t('The content can be scheduled, but will only be published after approval by the CEO.'), 'status', FALSE);
    }
  }
  return $allowed;
}
