<?php

/**
 * @file
 * Install and uninstall hooks for the Scheduler API Test module.
 */

/**
 * Implements hook_install().
 */
function scheduler_api_test_install() {
}

/**
 * Implements hook_uninstall().
 */
function scheduler_api_test_uninstall() {
  // Delete the custom node type and other config items.
  \Drupal::configFactory()->getEditable('node.type.scheduler_api_test')->delete();
  \Drupal::configFactory()->getEditable('field.storage.node.field_approved')->delete();
  \Drupal::configFactory()->getEditable('field.field.node.scheduler_api_test.field_approved')->delete();
  \Drupal::configFactory()->getEditable('core.entity_form_display.node.scheduler_api_test.default')->delete();
  \Drupal::configFactory()->getEditable('core.entity_view_display.node.scheduler_api_test.default')->delete();
  // @todo Is there a better way to delete the config items on uninstall?
  // Assumed this was automatic but it seems not. After manual uninstall the
  // node type is still available, and re-install fails.
  // Cannot re-install until these are removed.
}
