################
# DrupalCI includes:
# As long as you include this, any future includes added by the Drupal Association will be accessible to your pipelines automatically.
# View these include files at https://git.drupalcode.org/project/gitlab_templates/
################
include:
  - project: $_GITLAB_TEMPLATES_REPO
    ref: $_GITLAB_TEMPLATES_REF
    file:
      - '/includes/include.drupalci.main.yml'
      - '/includes/include.drupalci.variables.yml'
      - '/includes/include.drupalci.workflows.yml'

################
# Pipeline configuration variables
################
variables:
  OPT_IN_TEST_NEXT_MINOR: 1
  _SHOW_ENVIRONMENT_VARIABLES: 1
  _PHPUNIT_CONCURRENT: 1
  _PHPUNIT_TESTGROUPS: ''
  _PHPUNIT_PARAMETERS:
    value: ''
    description: 'Additional parameters for use in PHPUNIT parallel job matrix.'

################
# Job overrides
################

# -------------------------------- BUILD ---------------------------------------

composer:
  after_script:
    # Show the last three commits. Current directory /builds/project/scheduler ($CI_PROJECT_DIR) is correct.
    - pwd
    - git show -3 --stat

# -------------------------------- VALIDATE ------------------------------------

eslint:
  allow_failure: false

stylelint:
  allow_failure: false

phpcs:
  allow_failure: false

phpstan:
  after_script:
    - test -f phpstan.neon && echo "=== This is phpstan.neon ===" && cat phpstan.neon
    - php $CI_PROJECT_DIR/scripts/phpstan-baseline-summary.php phpstan-baseline-to-fix.neon

# Do not need to run phpstan twice.
phpstan (next minor):
  rules:
    - when: never

cspell:
  after_script:
    - WORDS=$CI_PROJECT_DIR/_cspell_unrecognized_words.txt
    - test -f $WORD && echo "=== This is $WORDS ===" && cat $WORDS || true

# -------------------------------- TEST ----------------------------------------

.scheduler-matrix: &scheduler-matrix
  parallel:
    matrix:
      # Run test groups in parallel. This also speeds up identification of failing tests.
      # @todo put back "scheduler_drush" when https://www.drupal.org/i/3359998 is solved.
      - _MATRIX_VALUE:
        - scheduler
        - scheduler_api
        # - scheduler_drush
        - scheduler_js
        - scheduler_kernel
        - scheduler_rules_integration

.scheduler-phpunit-rule: &scheduler-phpunit-rule
  # Re-define _PHPUNIT_EXTRA depending on the value of _PHPUNIT_CONCURRENT
  - if: '$_PHPUNIT_CONCURRENT == "0"'
    variables:
      # Specify parameters that will be passed to PHPUNIT (needs --group)
      _PHPUNIT_EXTRA: $_PHPUNIT_PARAMETERS --group $_MATRIX_VALUE
  - if: '$_PHPUNIT_CONCURRENT == "1"'
    variables:
      # Specify parameters that will be passed to RUN-TESTS.SH (without --group)
      _PHPUNIT_EXTRA: $_PHPUNIT_PARAMETERS $_MATRIX_VALUE

phpunit:
  <<: *scheduler-matrix
  rules:
    - !reference [ .opt-in-current-rule ]
    - !reference [ .skip-phpunit-rule ]
    - *scheduler-phpunit-rule
    - when: on_success
  after_script:
    # This is executed in all phpunit jobs because they extend phpunit (not .phpunit-base).
    # $WHAT_TO_RUN is not included because it is only derived in the phpunit script, so will always be blank here.
    - echo "_PHPUNIT_CONCURRENT=$_PHPUNIT_CONCURRENT, _PHPUNIT_TESTGROUPS=$_PHPUNIT_TESTGROUPS"
    - echo "_MATRIX_VALUE=$_MATRIX_VALUE, _PHPUNIT_EXTRA=$_PHPUNIT_EXTRA"

phpunit (next minor):
  rules:
    - !reference [ .opt-in-next-minor-rule ]
    - !reference [ .skip-phpunit-rule ]
    # Do not automatically run, but allow the job to be started manually.
    - when: manual
  # Cannot use parallel matrix when the job is triggered manually, because the
  # matrix values are not passed through. Therefore remove 'parallel' and run
  # the tests in one job. Cannot have _PHPUNIT_TESTGROUPS = --all because this
  # includes scheduler_drush. Therefore list all except that group.
  parallel:
  variables:
    _PHPUNIT_TESTGROUPS: 'scheduler, scheduler_api, scheduler_js, scheduler_kernel, scheduler_rules_integration'
    # Use core ignoreFile to show deprecations. This will only work with $_PHPUNIT_CONCURRENT=1
    _PHPUNIT_CONCURRENT: 1
    SYMFONY_DEPRECATIONS_HELPER: "ignoreFile=$CI_PROJECT_DIR/$_WEB_ROOT/core/.deprecation-ignore.txt"
  allow_failure: true
