<?php

/**
 * @file
 * Scheduler rules functions.
 */

use Drupal\Core\Url;
use Drupal\node\Entity\Node;

/**
 * Implements hook_rules_event_info().
 */
function scheduler_rules_event_info() {
  // This hook function defines four Scheduler events which can be used by Rules
  // to trigger other actions.

}

/**
 * Implements hook_rules_action_info().
 */
function scheduler_rules_action_info() {
}

