<?php

/**
 * @file
 * Scheduler publishes and unpublishes nodes on dates specified by the user.
 */

use Drupal\Component\Utility\Xss;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Url;
use Drupal\node\NodeInterface;
use Drupal\Core\Routing\RouteMatchInterface;

// @todo Move constants into a class, so we do not pollute the global space,
// and use them like this, for example: SchedulerApi::MY_CONSTANT.

// The default format to use if no custom format has been configured.
define('SCHEDULER_DATE_FORMAT', 'Y-m-d H:i:s');

// The default date and time formats to use when only a date has been entered.
// These should match the date and time parts of SCHEDULER_DATE_FORMAT above.
define('SCHEDULER_DATE_ONLY_FORMAT', 'Y-m-d');
define('SCHEDULER_TIME_ONLY_FORMAT', 'H:i:s');

// The default time that will be used, until Admin sets a different value.
define('SCHEDULER_DEFAULT_TIME', '00:00:00');

// The full set of date and time letters allowed in the scheduler date format.
define('SCHEDULER_DATE_LETTERS', 'djmnFMyY');
define('SCHEDULER_TIME_LETTERS', 'hHgGisaA');

// Specify defaults for the per-content-type settings. These should be used as
// a consistent third parameter for calls to getThirdPartySetting().
define('SCHEDULER_DEFAULT_PUBLISH_PAST_DATE', 'error');
define('SCHEDULER_DEFAULT_FIELDS_DISPLAY_MODE', 'vertical_tab');
define('SCHEDULER_DEFAULT_EXPAND_FIELDSET', 'when_required');

/**
 * Implements hook_menu().
 *
 * @deprecated Will be removed before the first alpha release.
 * @see https://www.drupal.org/node/2626480
 */
function scheduler_menu() {
  $items = array();
  $items['scheduler/cron'] = array(
    'title' => 'Lightweight cron handler',
    'description' => 'Run the lightweight cron process',
    'page callback' => '_scheduler_run_cron',
    'access callback' => '_scheduler_cron_access',
    'access arguments' => array(2),
    'type' => MENU_CALLBACK,
    'file' => 'scheduler.cron.inc',
  );
  return $items;
}

/**
 * Implements hook_help().
 */
function scheduler_help($route_name, RouteMatchInterface $route_match) {
  $output = '';
  switch ($route_name) {
    case 'help.page.scheduler':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('The Scheduler module provides the functionality for automatic publishing and unpublishing of nodes at specified future dates.') . '</p>';
      $output .= '<p>' . t('You can read more in the <a href="@readme">readme.txt</a> file.', array('@readme' => $GLOBALS['base_url'] . '/' . drupal_get_path('module', 'scheduler') . '/README.txt')) . '</p>';
      break;
    case 'scheduler.admin_form':
      $output = '<p>' . t('Some Scheduler options are set for each different content type, and are accessed via the <a href="@link">admin content type</a> list.', array('@link' => Url::fromRoute('entity.node_type.collection')->toString())) . '</br>';
      $output .= t('The options and settings below are common to all content types.') . '</p>';
      break;
    case 'scheduler.cron_form':
      $base_url = $GLOBALS['base_url'];
      $access_key = \Drupal::config('scheduler.settings')->get('lightweight_cron_access_key');
      $cron_url = $base_url . '/scheduler/cron' . ($access_key ? '/' . $access_key : '');
      $output = '<p>' . t("When you have set up Drupal's standard crontab job cron.php then Scheduler will be executed during each cron run. However, if you would like finer granularity to scheduler, but don't want to run Drupal's cron more often then you can use the lightweight cron handler provided by Scheduler. This is an independent cron job which only runs the scheduler process and does not execute any cron tasks defined by Drupal core or any other modules.") . '</p>';
      $output .= '<p>' . t("Scheduler's cron is at /scheduler/cron and a sample crontab entry to run scheduler every minute might look like:") . '</p>';
      $output .= '<code>* * * * * wget -q -O /dev/null "' . $cron_url . '"</code>';
      $output .= '<p>' . t('or') . '</p>';
      $output .= '<code>* * * * * curl -s -o /dev/null "' . $cron_url . '"</code><br/><br/>';
      break;
    default:
  }
  return $output;
}

/**
 * Implements hook_form_node_type_form_alter().
 */
function scheduler_form_node_type_form_alter(array &$form, FormStateInterface $form_state) {
  // Load the real code only when needed.
  module_load_include('inc', 'scheduler', 'scheduler.admin');
  _scheduler_form_node_type_form_alter($form, $form_state);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for node_form.
 */
function scheduler_form_node_form_alter(&$form, FormStateInterface $form_state) {
  $date_formatter = \Drupal::service('date.formatter');
  /** @var \Drupal\node\NodeTypeInterface $type */
  $type = $form_state->getFormObject()->getEntity()->type->entity;
  $publishing_enabled = $type->getThirdPartySetting('scheduler', 'publish_enable', FALSE);
  $unpublishing_enabled = $type->getThirdPartySetting('scheduler', 'unpublish_enable', FALSE);
  $use_vertical_tabs = $type->getThirdPartySetting('scheduler', 'fields_display_mode', SCHEDULER_DEFAULT_FIELDS_DISPLAY_MODE) === 'vertical_tab';

  $date_format = \Drupal::config('scheduler.settings')->get('date_format');
  $date_only_format = \Drupal::config('scheduler.settings')->get('date_only_format');
  $time_only_format = \Drupal::config('scheduler.settings')->get('time_only_format');
  $date_only_allowed = \Drupal::config('scheduler.settings')->get('allow_date_only');

  /* @var $node \Drupal\node\NodeInterface */
  $node = $form_state->getFormObject()->getEntity();

  // A publish_on date is required if the content type option is set and the
  // node is being created or it currently has a scheduled publishing date.
  $publishing_required = $type->getThirdPartySetting('scheduler', 'publish_required', FALSE)
    && ($node->isNew() || (!$node->isPublished() && !empty($node->publish_on->value)));

  // An unpublish_on date is required if the content type option is set and the
  // node is being created or the current status is published or the node is
  // scheduled to be published.
  $unpublishing_required = $type->getThirdPartySetting('scheduler', 'unpublish_required', FALSE) && ($node->isNew() || $node->isPublished() || !empty($node->publish_on->value));

  // If either publishing or unpublishing is enabled, provide a field group to
  // wrap the scheduling fields.
  if ($publishing_enabled || $unpublishing_enabled) {
    // Expand the fieldset if publishing or unpublishing is required, if a date
    // already exists or the fieldset is configured to be always expanded.
    $has_data = !empty($node->publish_on->value) || !empty($node->unpublish_on->value);
    $always_expand = $type->getThirdPartySetting('scheduler', 'expand_fieldset', SCHEDULER_DEFAULT_EXPAND_FIELDSET) === 'always';
    $expand_details = $publishing_required || $unpublishing_required || $has_data || $always_expand;

    // Create the group for the fields.
    $form['scheduler_settings'] = array(
      '#type' => 'details',
      '#title' => t('Scheduling options'),
      '#open' => $expand_details,
      '#weight' => 35,
      '#attributes' => array(
        'class' => array('scheduler-form'),
      ),
      '#optional' => FALSE,
    );

    // Attach the fields to group.
    $form['unpublish_on']['#group'] = 'scheduler_settings';
    $form['publish_on']['#group'] = 'scheduler_settings';

    // Show the field group as a vertical tab if this option is enabled.
    if ($use_vertical_tabs) {
      $form['scheduler_settings']['#group'] = 'advanced';

      // Attach the javascript for the vertical tabs.
      $form['scheduler_settings']['#attached']['library'][] = 'scheduler/vertical-tabs';
    }
  }

  // Define the descriptions depending on whether the time can be skipped.
  $descriptions = array();
  if ($date_only_allowed && ($date_only_format != $date_format)) {
    $descriptions['format'] = t('Format: %date_only_format or %standard_format.', array(
      '%date_only_format' => $date_formatter->format(time(), 'custom', $date_only_format),
      '%standard_format' => $date_formatter->format(time(), 'custom', $date_format),
    ));
  }
  else {
    $descriptions['format'] = t('Format: %standard_format.', array(
      '%standard_format' => $date_formatter->format(time(), 'custom', $date_format),
    ));
  }

  // Show the default time so users know what they will get if they do not enter
  // a time.
  if ($date_only_allowed) {
    $default_time = strtotime(\Drupal::config('scheduler.settings')->get('default_time'));
    $descriptions['default'] = t('The default time is @default_time.', array(
      '@default_time' => $date_formatter->format($default_time, 'custom', $time_only_format ? $time_only_format : SCHEDULER_TIME_ONLY_FORMAT),
    ));
  }

  if (!$publishing_required) {
    $descriptions['blank'] = t('Leave the date blank for no scheduled publishing.');
  }

  $form['publish_on']['#access'] = $publishing_enabled;
  $form['publish_on']['widget'][0]['value']['#required'] = $publishing_required;
  $form['publish_on']['widget'][0]['value']['#description'] = Xss::filter(implode(' ', $descriptions));

  if (!$unpublishing_required) {
    $descriptions['blank'] = t('Leave the date blank for no scheduled unpublishing.');
  }
  else {
    unset($descriptions['blank']);
  }

  $form['unpublish_on']['#access'] = $unpublishing_enabled;
  $form['unpublish_on']['widget'][0]['value']['#required'] = $unpublishing_required;
  $form['unpublish_on']['widget'][0]['value']['#description'] = Xss::filter(implode(' ', $descriptions));
}

/**
 * Implements hook_entity_base_field_info().
 */
function scheduler_entity_base_field_info(EntityTypeInterface $entity_type) {
  if ($entity_type->id() === 'node') {
    $fields['publish_on'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(t('Publish on'))
      ->setDisplayOptions('form', [
        'type' => 'datetime_timestamp_no_default',
        'weight' => 30,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE)
      ->addConstraint('SchedulerPublishOn');

    $fields['unpublish_on'] = BaseFieldDefinition::create('timestamp')
      ->setLabel(t('Unpublish on'))
      ->setDisplayOptions('form', [
        'type' => 'datetime_timestamp_no_default',
        'weight' => 30,
      ])
      ->setDisplayConfigurable('form', TRUE)
      ->setTranslatable(TRUE)
      ->setRevisionable(TRUE)
      ->addConstraint('SchedulerUnpublishOn');

    return $fields;
  }
}

/**
 * Checks whether a scheduled action on a node is allowed.
 *
 * This provides a way for other modules to prevent scheduled publishing or
 * unpublishing, by implementing hook_scheduler_allow_publishing() or
 * hook_scheduler_allow_unpublishing().
 *
 * @deprecated Will be moved to a service.
 *
 * @see https://www.drupal.org/node/2651338
 * @see hook_scheduler_allow_publishing()
 * @see hook_scheduler_allow_unpublishing()
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node on which the action is to be performed.
 * @param string $action
 *   The action that needs to be checked. Can be 'publish' or 'unpublish'.
 *
 * @return bool
 *   TRUE if the action is allowed, FALSE if not.
 */
function _scheduler_allow(NodeInterface $node, $action) {
  // Default to TRUE.
  $result = TRUE;
  // Check that other modules allow the action.
  $hook = 'scheduler_allow_' . $action . 'ing';
  foreach (\Drupal::moduleHandler()->getImplementations($hook) as $module) {
    $function = $module . '_' . $hook;
    $result &= $function($node);
  }

  return $result;
}

/**
 * Implements hook_ENTITY_TYPE_view() for node entities.
 */
function scheduler_node_view(array &$build, EntityInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  // If the node is going to be unpublished then add this information to the
  // header for googlebot. Only do this when the current page is the full-page
  // view of the node.
  if (!empty($node->unpublish_on->value) && node_is_page($node)) {
    $unavailable_after = date('d-M-Y H:i:s T', $node->unpublish_on->value);
    $metatag = [
      '#tag' => 'meta',
      '#attributes' => [
        'name' => 'googlebot',
        'content' => 'unavailable_after: ' . $unavailable_after,
      ],
    ];
    $build['#attached']['html_head'][] = [$metatag, 'scheduler_unavailable'];
  }
}

/**
 * Implements hook_node_validate().
 *
 * @deprecated hook_node_validate() and hook_node_submit() have been removed.
 *
 * @see https://www.drupal.org/node/2420295
 * @see https://www.drupal.org/node/2490570
 * @see https://www.drupal.org/node/2490578
 */
function scheduler_node_validate($node, array $form, FormStateInterface $form_state) {
  // Adjust the entered times for timezone consideration. Note, we must check
  // to see if the value is numeric. If it is, assume we have already done the
  // strtotime conversion. This prevents us running strtotime on a value we have
  // already converted. This is needed because Drupal 6 removed 'submit' and
  // added 'presave' and all this happens at different times.
  $date_format = \Drupal::config('scheduler.settings')->get('date_format');
  $date_formatter = \Drupal::service('date.formatter');
  $entity = $node->type->entity;

  if (!empty($node->publish_on->value) && !is_numeric($node->publish_on->value)) {
    $publishtime = $node->publish_on->value;
    if ($publishtime === FALSE) {
      $form_state->setErrorByName('publish_on', t("The 'publish on' value does not match the expected format of %time",
        array('%time' => $date_formatter->format(REQUEST_TIME, 'custom', $date_format))
      ));
    }
  }

  if (!empty($node->unpublish_on->value) && !is_numeric($node->unpublish_on->value)) {
    $unpublishtime = $node->unpublish_on->value;
    if ($unpublishtime === FALSE) {
      $form_state->setErrorByName('unpublish_on', t("The 'unpublish on' value does not match the expected format of %time",
        array('%time' => $date_formatter->format(REQUEST_TIME, 'custom', $date_format))
      ));
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_presave() for node entities.
 */
function scheduler_node_presave(EntityInterface $node) {
  $date_formatter = \Drupal::service('date.formatter');
  if ($node->publish_on->value > 0) {
    // Check that other modules allow the action on this node.
    $publication_allowed = _scheduler_allow($node, 'publish');

    // Publish the node immediately if the publication date is in the past.
    $entity = $node->type->entity;
    $publish_immediately = $entity->getThirdPartySetting('scheduler', 'publish_past_date', SCHEDULER_DEFAULT_PUBLISH_PAST_DATE) == 'publish';

    if ($publication_allowed && $publish_immediately && $node->publish_on->value <= REQUEST_TIME) {
      // If required, set the created date to match published date.
      if ($entity->getThirdPartySetting('scheduler', 'publish_touch', 0)) {
        $node->setCreatedTime($node->publish_on->value);
      }
      $node->publish_on->value = 0;
      $node->setPublished(TRUE);
      // Allow modules to react to immediate publishing.
      _scheduler_scheduler_api($node, 'publish_immediately');
    }
    else {
      // Ensure the node is unpublished as it will be published by cron later.
      $node->setPublished(FALSE);

      // Only inform the user that the node is scheduled if publication has not
      // been prevented by other modules. Those modules have to display a
      // message themselves explaining why publication is denied.
      if ($publication_allowed) {
        $date_format = \Drupal::config('scheduler.settings')->get('date_format');
        drupal_set_message(t('This post is unpublished and will be published @publish_time.',
          array('@publish_time' => $date_formatter->format($node->publish_on->value, 'custom', $date_format))), 'status', FALSE);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_insert() for node entities.
 *
 * @todo Still needs to be ported to Drupal 8.
 *
 * @see https://www.drupal.org/node/2651348
 */
function scheduler_node_insert(EntityInterface $node) {
  // Only insert into database if we need to (un)publish this node at some date.
  if (!empty($node->publish_on->value) || !empty($node->unpublish_on->value)) {
    // Invoke the events to indicate that a new node has been scheduled.
    if (\Drupal::moduleHandler()->moduleExists('rules')) {
      if (!empty($node->publish_on->value)) {
        rules_invoke_event('scheduler_new_node_is_scheduled_for_publishing_event', $node, $node->publish_on->value, $node->unpublish_on->value);
      }
      if (!empty($node->unpublish_on->value)) {
        rules_invoke_event('scheduler_new_node_is_scheduled_for_unpublishing_event', $node, $node->publish_on->value, $node->unpublish_on->value);
      }
    }
  }
}

/**
 * Implements hook_ENTITY_TYPE_update() for node entities.
 *
 * @todo Still needs to be ported to Drupal 8.
 *
 * @see https://www.drupal.org/node/2651348
 */
function scheduler_node_update(EntityInterface $node) {
  if (!empty($node->publish_on->value) || !empty($node->unpublish_on->value)) {
    // Invoke the events to indicate that an existing node has been scheduled.
    if (\Drupal::moduleHandler()->moduleExists('rules')) {
      if (!empty($node->publish_on->value)) {
        rules_invoke_event('scheduler_existing_node_is_scheduled_for_publishing_event', $node, $node->publish_on->value, $node->unpublish_on->value);
      }
      if (!empty($node->unpublish_on->value)) {
        rules_invoke_event('scheduler_existing_node_is_scheduled_for_unpublishing_event', $node, $node->publish_on->value, $node->unpublish_on->value);
      }
    }
  }
}

/**
 * Implements hook_cron().
 */
function scheduler_cron() {
  // Load the cron functions file.
  module_load_include('inc', 'scheduler', 'scheduler.cron');

  // Use drupal_static so that any function can find out if we are running
  // Scheduler cron. Set the default value to FALSE, then turn on the flag.
  // @see scheduler_cron_is_running()
  $scheduler_cron = &drupal_static(__FUNCTION__, FALSE);
  $scheduler_cron = TRUE;

  _scheduler_publish();
  _scheduler_unpublish();

  // Reset the static scheduler_cron flag.
  drupal_static_reset(__FUNCTION__);
}

/**
 * Return whether Scheduler cron is running.
 *
 * This function can be called from any Scheduler function, from any contrib
 * module or from custom PHP in a view or rule.
 *
 * @return bool
 *   TRUE if scheduler_cron is currently running. FALSE if not.
 */
function scheduler_cron_is_running() {
  return drupal_static('scheduler_cron');
}

/**
 * Access callback for the lightweight cron url /scheduler/cron/key.
 *
 * @param string $cron_key
 *   The cron key that was passed as a URL argument.
 *
 * @return bool
 *   TRUE if the cron url key is correct. FALSE otherwise.
 */
function _scheduler_cron_access($cron_key) {
  $valid_cron_key = \Drupal::config('scheduler.settings')->get('lightweight_cron_access_key');
  return $valid_cron_key == $cron_key;
}

/**
 * Scheduler API to perform actions when nodes are (un)published.
 *
 * This allows other modules to implement hook_scheduler_api($node, $action).
 *
 * @param \Drupal\node\NodeInterface $node
 *   The node object.
 * @param string $action
 *   The action being performed, either 'pre_publish', 'publish',
 *   'publish_immediately', 'pre_unpublish' or 'unpublish'.
 *
 * @deprecated Will be moved to a service.
 *
 * @see https://www.drupal.org/node/2651338
 */
function _scheduler_scheduler_api(NodeInterface $node, $action) {
  foreach (\Drupal::moduleHandler()->getImplementations('scheduler_api') as $module) {
    $function = $module . '_scheduler_api';
    $function($node, $action);
  }
}

/**
 * Prepares variables for node templates.
 *
 * Makes the publish_on and unpublish_on data available as theme variables.
 *
 * @see template_preprocess_node()
 */
function scheduler_preprocess_node(&$variables) {
  $date_formatter = \Drupal::service('date.formatter');
  /* @var $node \Drupal\node\NodeInterface */
  $node = $variables['node'];
  $date_format = \Drupal::config('scheduler.settings')->get('date_format');
  if (!empty($node->publish_on->value) && $node->publish_on->value && is_numeric($node->publish_on->value)) {
    $variables['publish_on'] = $date_formatter->format($node->publish_on->value, 'custom', $date_format);
  }
  if (!empty($node->unpublish_on->value) && $node->unpublish_on->value && is_numeric($node->unpublish_on->value)) {
    $variables['unpublish_on'] = $date_formatter->format($node->unpublish_on->value, 'custom', $date_format);
  }
}

/**
 * Implements hook_feeds_processor_targets_alter().
 *
 * This function exposes publish_on and unpublish_on as mappable targets to the
 * Feeds module.
 *
 * @todo Port to Drupal 8.
 *
 * @see https://www.drupal.org/node/2651354
 */
function scheduler_feeds_processor_targets_alter(&$targets, $entity_type, $bundle_name) {
  // Scheduler module only works on nodes.
  if ($entity_type == 'node') {
    $publishing_enabled = $entity_type->getThirdPartySetting('scheduler', 'publish_enable', 0);
    $unpublishing_enabled = $entity_type->getThirdPartySetting('scheduler', 'unpublish_enable', 0);

    if ($publishing_enabled) {
      $targets['publish_on'] = array(
        'name' => t('Scheduler: publish on'),
        'description' => t('The date when the Scheduler module will publish the node.'),
        'callback' => 'scheduler_feeds_set_target',
      );
    }
    if ($unpublishing_enabled) {
      $targets['unpublish_on'] = array(
        'name' => t('Scheduler: unpublish on'),
        'description' => t('The date when the Scheduler module will unpublish the node.'),
        'callback' => 'scheduler_feeds_set_target',
      );
    }
  }
}

/**
 * Mapping callback for the Feeds module.
 *
 * @todo Port to Drupal 8.
 *
 * @see https://www.drupal.org/node/2651354
 */
function scheduler_feeds_set_target($source, $entity, $target, $value, $mapping) {
  // We expect a string or integer, but can accomodate an array, by taking the
  // first item. Use trim() so that a string of blanks is reduced to empty.
  $value = is_array($value) ? trim(reset($value)) : trim($value);

  // Convert input from parser to timestamp form. If $value is empty or blank
  // then strtotime() must not be used, otherwise it returns the current time.
  if (!empty($value) && !is_numeric($value)) {
    if (!$timestamp = strtotime($value)) {
      throw new FeedsValidationException(
        // Throw an exception if the date format was not recognized.
        t('Value %value for @source could not be converted to a valid %target date.', array(
          '@source' => $mapping['source'],
          '%value' => $value,
          '%target' => $target,
        )
      ));
    }
  }
  else {
    $timestamp = $value;
  }

  // If the timestamp is valid then use it to set the target field in the node.
  if (is_numeric($timestamp) && $timestamp > 0) {
    $entity->$target = $timestamp;
  }
}
